name: 'Get & Cache dependencies'
description: "Optional"
inputs:
  use_caching:
    description: ""
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.use_caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.use_caching != 'true'
      shell: bash
      run: npm ci
