name: JS Custom Action
on:
  workflow_dispatch:
jobs:
  information:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v3
    - name: Run js action
      id: setup-java
      uses: ./.github/actions/js-action
      with:
        java-version: '17'
        distribution: 'oracle'
        java-package: 'jdk'
    - name: Output information
      run: |
        echo "Action output: ${{ steps.setup-java.outputs.version }}"
        echo "Action output: ${{ steps.setup-java.outputs.distribution }}"
        echo "Action output: ${{ steps.setup-java.outputs.path }}"