name: Deployment
on:
  push:
    branches:
      - main
jobs:
  information:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v3
    - name: Run js action
      uses: ./.github/actions/ts-action
      with:
        java-version: '17'
        distribution: 'oracle'
        java-package: 'jdk'