name: TS Custom Action
on:
  workflow_dispatch:
jobs:
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Run ts action
        id: setup-java
        uses: ./.github/actions/ts-custom-action
        with:
          java-version: '17'
          distribution: 'blubb'
          java-package: 'jdk'
      - name: Output information
        run: |
          echo "Action output: ${{ steps.setup-java.outputs.version }}"
          echo "Action output: ${{ steps.setup-java.outputs.distribution }}"
          echo "Action output: ${{ steps.setup-java.outputs.path }}"